default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: pair_bnb_development


test:
  <<: *default
  database: pair_bnb_test


production:
  <<: *default
  database: pair_bnb_production
  username: pair_bnb
  password: <%= ENV['SHOUTER_DATABASE_PASSWORD'] %>